// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiCRUDOps;

#nullable disable

namespace WebApiCRUDOps.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250526210043_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiCRUDOps.DataUtility.Model.PdfUpload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("CompressedPdf")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("OriginalPdf")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("PdfUploads");
                });

            modelBuilder.Entity("WebApiCRUDOps.DataUtility.Model.Person", b =>
                {
                    b.Property<int>("personId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("personId"));

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("price")
                        .HasColumnType("float");

                    b.Property<int>("size")
                        .HasColumnType("int");

                    b.HasKey("personId");

                    b.ToTable("personDetail");

                    b.HasData(
                        new
                        {
                            personId = 1,
                            firstName = "blue",
                            gender = "men",
                            lastName = "Arrow",
                            price = 49.990000000000002,
                            size = 28
                        },
                        new
                        {
                            personId = 2,
                            firstName = "paleblue",
                            gender = "men",
                            lastName = "PeterEngland",
                            price = 119.98999999999999,
                            size = 38
                        },
                        new
                        {
                            personId = 3,
                            firstName = "marron",
                            gender = "men",
                            lastName = "Jameshamstephedan",
                            price = 49.990000000000002,
                            size = 42
                        },
                        new
                        {
                            personId = 4,
                            firstName = "BabyPinkishBlue",
                            gender = "women",
                            lastName = "Zara",
                            price = 149.99000000000001,
                            size = 28
                        });
                });

            modelBuilder.Entity("WebApiCRUDOps.DataUtility.Model.PdfUpload", b =>
                {
                    b.HasOne("WebApiCRUDOps.DataUtility.Model.Person", "Person")
                        .WithMany("PdfUploads")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("WebApiCRUDOps.DataUtility.Model.Person", b =>
                {
                    b.Navigation("PdfUploads");
                });
#pragma warning restore 612, 618
        }
    }
}
